export const handler = async () => ({
  statusCode: 200,
  headers: { "Access-Control-Allow-Origin": "*", "Content-Type": "application/json" },
  body: JSON.stringify({
    agents: [
      { id: "research-001", name: "Research Agent", type: "research", status: "running", maxPods: 10,
        description: "Searches, scrapes, and synthesizes knowledge on any topic using RAG + LLM.",
        plugins: ["Pinecone RAG", "Web Scraper", "Tavily Search"],
        pipeline: ["Receive Query", "Vector Search", "Fetch Docs", "LLM Synthesis", "Return Report"] },
      { id: "email-001", name: "Email Agent", type: "email", status: "running", maxDuration: 3,
        description: "Reads, drafts, categorizes and sends emails autonomously.",
        plugins: ["Gmail API", "SendGrid", "NLP Classifier"],
        pipeline: ["Parse Intent", "Compose Draft", "Review Context", "Send/Queue", "Log Event"] },
      { id: "finance-001", name: "Finance Agent", type: "finance", status: "running", maxPods: 5,
        description: "Market analysis, portfolio alerts, financial reporting.",
        plugins: ["Alpha Vantage", "Yahoo Finance", "Stripe API"],
        pipeline: ["Fetch Market Data", "Run Analysis", "RAG Context", "Generate Insight", "Alert/Report"] },
      { id: "data-001", name: "Data Pipeline Agent", type: "data", status: "running", maxPods: 7,
        description: "ETL pipelines, data cleaning, ML feature engineering.",
        plugins: ["Apache Kafka", "Airflow", "Kubeflow"],
        pipeline: ["Ingest Source", "Transform", "Validate Schema", "Load to DB", "Trigger ML Run"] },
      { id: "summary-001", name: "Summarization Agent", type: "summarization", status: "running", maxPods: 4,
        description: "Condenses long documents and reports into actionable summaries.",
        plugins: ["Claude API", "PDF Parser"],
        pipeline: ["Receive Document", "Chunk Text", "Embed Chunks", "Summarize", "Return Summary"] },
      { id: "matching-001", name: "Matching Agent", type: "matching", status: "idle", maxPods: 4,
        description: "Semantic matching, recommendation, compatibility scoring.",
        plugins: ["Weaviate VectorDB", "OpenAI Embeddings"],
        pipeline: ["Embed Profile", "Cosine Search", "Score Matches", "Rank Results", "Return List"] },
    ],
  }),
});
